export interface Product {
  id: number;
  name: string;
  category: string;
  categorySlug: string;
  price: number;
  image: string;
  description: string;
  dosage: string;
  manufacturer: string;
  stock: number;
  badge?: string;
}

export interface Category {
  id: number;
  name: string;
  slug: string;
  icon: string;
  count: number;
  color: string;
}

export const categories: Category[] = [
  { id: 1, name: "Obat Bebas", slug: "obat-bebas", icon: "💊", count: 45, color: "#2563EB" },
  { id: 2, name: "Vitamin & Suplemen", slug: "vitamin-suplemen", icon: "🫐", count: 38, color: "#7C3AED" },
  { id: 3, name: "Obat Keras", slug: "obat-keras", icon: "💉", count: 27, color: "#DC2626" },
  { id: 4, name: "Herbal & Tradisional", slug: "herbal-tradisional", icon: "🌿", count: 31, color: "#16A34A" },
  { id: 5, name: "Perawatan Kulit", slug: "perawatan-kulit", icon: "🧴", count: 22, color: "#DB2777" },
  { id: 6, name: "Alat Kesehatan", slug: "alat-kesehatan", icon: "🩺", count: 19, color: "#0891B2" },
  { id: 7, name: "Obat Mata & THT", slug: "obat-mata-tht", icon: "👁️", count: 15, color: "#9333EA" },
  { id: 8, name: "P3K & Antiseptik", slug: "p3k-antiseptik", icon: "🩹", count: 24, color: "#EA580C" },
];

export const products: Product[] = [
  {
    id: 1,
    name: "Paracetamol 500mg",
    category: "Obat Bebas",
    categorySlug: "obat-bebas",
    price: 15000,
    image: "/products/paracetamol.jpg",
    description: "Paracetamol 500mg digunakan untuk meredakan demam dan nyeri ringan hingga sedang, seperti sakit kepala, sakit gigi, nyeri otot, dan nyeri menstruasi. Bekerja dengan menghambat produksi prostaglandin di otak yang menyebabkan rasa sakit dan demam.",
    dosage: "Dewasa: 1-2 tablet, 3-4x sehari. Anak-anak: sesuai petunjuk dokter.",
    manufacturer: "Kimia Farma",
    stock: 150,
    badge: "Terlaris",
  },
  {
    id: 2,
    name: "Amoxicillin 500mg",
    category: "Obat Keras",
    categorySlug: "obat-keras",
    price: 45000,
    image: "/products/amoxicillin.jpg",
    description: "Amoxicillin 500mg adalah antibiotik golongan penicillin yang digunakan untuk mengobati infeksi bakteri seperti infeksi saluran pernapasan, infeksi kulit, infeksi saluran kemih, dan infeksi lainnya.",
    dosage: "Dewasa: 250-500mg setiap 8 jam. Harus dengan resep dokter.",
    manufacturer: "Dexa Medica",
    stock: 80,
    badge: "Resep Dokter",
  },
  {
    id: 3,
    name: "Vitamin C 1000mg Effervescent",
    category: "Vitamin & Suplemen",
    categorySlug: "vitamin-suplemen",
    price: 89000,
    image: "/products/vitamin-c.jpg",
    description: "Vitamin C 1000mg Effervescent diformulasikan untuk meningkatkan daya tahan tubuh, sebagai antioksidan, membantu pembentukan kolagen, dan mempercepat penyembuhan luka. Tersedia dalam rasa orange yang segar.",
    dosage: "1 tablet efferescent per hari, larutkan dalam 200ml air.",
    manufacturer: "Redoxon",
    stock: 200,
    badge: "Promo",
  },
  {
    id: 4,
    name: "Minyak Kayu Putih 100ml",
    category: "Herbal & Tradisional",
    categorySlug: "herbal-tradisional",
    price: 25000,
    image: "/products/kayu-putih.jpg",
    description: "Minyak Kayu Putih murni 100ml dari ekstrak daun kayu putih pilihan. Cocok untuk mengatasi masuk angin, meredakan perut kembung, nyeri otot, dan memberikan sensasi hangat yang nyaman.",
    dosage: "Oleskan secukupnya pada bagian yang sakit atau dihirup.",
    manufacturer: "Cap Lang",
    stock: 120,
  },
  {
    id: 5,
    name: "Betadine Antiseptic 100ml",
    category: "P3K & Antiseptik",
    categorySlug: "p3k-antiseptik",
    price: 35000,
    image: "/products/betadine.jpg",
    description: "Betadine Antiseptik mengandung Povidone-Iodine 10% untuk membersihkan dan mencegah infeksi pada luka. Efektif melawan bakteri, virus, jamur, dan spora. Aman digunakan untuk luka ringan sehari-hari.",
    dosage: "Oleskan pada luka 1-3x sehari setelah luka dibersihkan.",
    manufacturer: "Mahapharm",
    stock: 95,
    badge: "Terlaris",
  },
  {
    id: 6,
    name: "Cetirizine 10mg",
    category: "Obat Bebas",
    categorySlug: "obat-bebas",
    price: 28000,
    image: "/products/cetirizine.jpg",
    description: "Cetirizine 10mg adalah antihistamin generasi kedua yang digunakan untuk meredakan gejala alergi seperti pilek, bersin, mata gatal, gatal-gatal pada kulit, dan urtikaria. Tidak menyebabkan kantuk berlebih.",
    dosage: "Dewasa dan anak > 12 tahun: 1 tablet per hari.",
    manufacturer: "Hexpharm Jaya",
    stock: 110,
  },
  {
    id: 7,
    name: "Wardah Sunscreen SPF 50+",
    category: "Perawatan Kulit",
    categorySlug: "perawatan-kulit",
    price: 65000,
    image: "/products/sunscreen.jpg",
    description: "Sunscreen dengan SPF 50+ PA++++ yang memberikan perlindungan optimal dari sinar UVA dan UVB. Formula ringan, tidak lengket, dan cocok untuk semua jenis kulit termasuk kulit sensitif. Dengan kandungan niacinamide untuk mencerahkan kulit.",
    dosage: "Oleskan secukupnya 15-20 menit sebelum aktivitas luar ruangan. Reapply setiap 2-3 jam.",
    manufacturer: "Wardah",
    stock: 75,
    badge: "Promo",
  },
  {
    id: 8,
    name: "Tensimeter Digital Omron",
    category: "Alat Kesehatan",
    categorySlug: "alat-kesehatan",
    price: 450000,
    image: "/products/tensimeter.jpg",
    description: "Tensimeter digital Omron HEM-7120 untuk mengukur tekanan darah dan denyut nadi secara akurat di rumah. Dilengkapi teknologi IntelliSense, mudah digunakan, dan menyimpan hingga 60 data pengukuran.",
    dosage: "Gunakan sesuai panduan penggunaan dalam kemasan.",
    manufacturer: "Omron",
    stock: 30,
  },
  {
    id: 9,
    name: "Stimuno Forte 30 Kapsul",
    category: "Herbal & Tradisional",
    categorySlug: "herbal-tradisional",
    price: 78000,
    image: "/products/stimuno.jpg",
    description: "Stimuno Forte mengandung ekstrak Phyllanthus niruri (meniran) yang telah terbukti secara klinis meningkatkan sistem imun tubuh. Membantu tubuh melawan infeksi virus dan bakteri secara alami.",
    dosage: "Dewasa: 1 kapsul, 3x sehari.",
    manufacturer: "Dexa Medica",
    stock: 145,
    badge: "Unggulan",
  },
  {
    id: 10,
    name: "Insto Eye Drops 7.5ml",
    category: "Obat Mata & THT",
    categorySlug: "obat-mata-tht",
    price: 22000,
    image: "/products/insto.jpg",
    description: "Insto Obat Tetes Mata mengandung Tetrahidrozolin HCl dan Benzalkonium Cl untuk meredakan mata merah akibat iritasi ringan karena debu, sengatan matahari, atau pemakaian lensa kontak.",
    dosage: "Teteskan 1-2 tetes pada mata 3-4x sehari atau sesuai petunjuk dokter.",
    manufacturer: "Combiphar",
    stock: 88,
  },
  {
    id: 11,
    name: "Enervon-C Multivitamin",
    category: "Vitamin & Suplemen",
    categorySlug: "vitamin-suplemen",
    price: 55000,
    image: "/products/enervon.jpg",
    description: "Enervon-C mengandung Vitamin B Kompleks, Vitamin C, dan Niacinamide untuk mendukung metabolisme energi, meningkatkan daya tahan tubuh, dan menjaga kesehatan kulit. Cocok untuk orang aktif.",
    dosage: "1 tablet per hari, diminum setelah makan.",
    manufacturer: "Abbott",
    stock: 180,
    badge: "Terlaris",
  },
  {
    id: 12,
    name: "Nivea Body Lotion Extra White",
    category: "Perawatan Kulit",
    categorySlug: "perawatan-kulit",
    price: 42000,
    image: "/products/nivea.jpg",
    description: "Nivea Body Lotion Extra White dengan formula licorice extract dan vitamin C untuk mencerahkan kulit secara merata. Memberikan kelembaban 48 jam dan membuat kulit tampak lebih cerah dan bercahaya.",
    dosage: "Oleskan secukupnya pada kulit setelah mandi dan sesuai kebutuhan.",
    manufacturer: "Beiersdorf",
    stock: 65,
  },
  {
    id: 13,
    name: "Ibuprofen 400mg",
    category: "Obat Bebas",
    categorySlug: "obat-bebas",
    price: 20000,
    image: "/products/ibuprofen.jpg",
    description: "Ibuprofen 400mg termasuk NSAID yang meredakan nyeri ringan hingga sedang, demam, dan peradangan. Efektif untuk sakit kepala, nyeri gigi, nyeri haid, dan nyeri otot.",
    dosage: "Dewasa: 1-2 tablet, 3x sehari setelah makan.",
    manufacturer: "Kalbe Farma",
    stock: 130,
  },
  {
    id: 14,
    name: "Masker N95 Medical Grade",
    category: "P3K & Antiseptik",
    categorySlug: "p3k-antiseptik",
    price: 35000,
    image: "/products/masker.jpg",
    description: "Masker N95 Medical Grade yang memfilter minimal 95% partikel airborne. Dilengkapi dengan adjustable nose clip dan elastis earloop untuk kenyamanan maksimal. Per pack isi 5 pcs.",
    dosage: "Gunakan sekali pakai, ganti setiap 8 jam atau bila sudah lembap.",
    manufacturer: "3M",
    stock: 200,
    badge: "Unggulan",
  },
  {
    id: 15,
    name: "Cough Syrup Bisolvon",
    category: "Obat Bebas",
    categorySlug: "obat-bebas",
    price: 48000,
    image: "/products/bisolvon.jpg",
    description: "Bisolvon Sirup mengandung Bromhexine HCl untuk mengencerkan dahak dan memudahkan pengeluaran dahak pada batuk berdahak. Tersedia dalam kemasan 60ml dengan rasa yang menyenangkan.",
    dosage: "Dewasa: 10ml, 3x sehari. Anak > 6 tahun: 5ml, 3x sehari.",
    manufacturer: "Boehringer Ingelheim",
    stock: 70,
  },
  {
    id: 16,
    name: "Glucometer Accu-Chek",
    category: "Alat Kesehatan",
    categorySlug: "alat-kesehatan",
    price: 320000,
    image: "/products/glucometer.jpg",
    description: "Glucometer Accu-Chek Active untuk pemantauan kadar gula darah di rumah. Hasil akurat dalam 5 detik, membutuhkan sampel darah minimal, layar besar mudah dibaca, memori 500 hasil.",
    dosage: "Gunakan sesuai panduan penggunaan dalam kemasan.",
    manufacturer: "Roche",
    stock: 25,
  },
  {
    id: 17,
    name: "Antangin JRG Herbal",
    category: "Herbal & Tradisional",
    categorySlug: "herbal-tradisional",
    price: 18000,
    image: "/products/antangin.jpg",
    description: "Antangin JRG mengandung jahe, rempah-rempah pilihan seperti kayu manis dan cengkeh yang dipercaya untuk mengatasi masuk angin, mual, dan perut kembung secara alami.",
    dosage: "2 kapsul, 3x sehari atau sesuai kebutuhan.",
    manufacturer: "Deltomed",
    stock: 160,
    badge: "Terlaris",
  },
  {
    id: 18,
    name: "Visine Eye Drops",
    category: "Obat Mata & THT",
    categorySlug: "obat-mata-tht",
    price: 30000,
    image: "/products/visine.jpg",
    description: "Visine tetes mata yang mengandung Tetrahidrozolin HCl untuk meringankan iritasi mata, mengurangi kemerahan, dan memberikan rasa segar. Cocok untuk pengguna komputer dan lensa kontak.",
    dosage: "Teteskan 1-2 tetes pada mata yang iritasi, 3-4x sehari.",
    manufacturer: "Johnson & Johnson",
    stock: 55,
  },
  {
    id: 19,
    name: "Omega-3 Fish Oil 1000mg",
    category: "Vitamin & Suplemen",
    categorySlug: "vitamin-suplemen",
    price: 125000,
    image: "/products/omega3.jpg",
    description: "Omega-3 Fish Oil 1000mg dengan kandungan EPA 180mg dan DHA 120mg per kapsul untuk mendukung kesehatan jantung, otak, dan sendi. Diproduksi dari ikan laut dalam berkualitas tinggi.",
    dosage: "1-2 kapsul per hari bersama makanan.",
    manufacturer: "Nature's Plus",
    stock: 90,
    badge: "Promo",
  },
  {
    id: 20,
    name: "Betamethasone Cream",
    category: "Obat Keras",
    categorySlug: "obat-keras",
    price: 38000,
    image: "/products/betamethasone.jpg",
    description: "Betamethasone Cream 0.1% adalah kortikosteroid topikal untuk mengatasi peradangan kulit, eksim, psoriasis, dan dermatitis. Efektif meredakan gatal, kemerahan, dan bengkak pada kulit.",
    dosage: "Oleskan tipis-tipis 1-2x sehari pada area yang sakit. Hanya atas rekomendasi dokter.",
    manufacturer: "Kimia Farma",
    stock: 60,
    badge: "Resep Dokter",
  },
  {
    id: 21,
    name: "Plester Luka Hansaplast",
    category: "P3K & Antiseptik",
    categorySlug: "p3k-antiseptik",
    price: 16000,
    image: "/products/hansaplast.jpg",
    description: "Hansaplast Classic Plester Luka berkualitas tinggi dengan bantalan yang lembut dan berpori untuk mempercepat penyembuhan luka. Isi 20 pcs dengan berbagai ukuran.",
    dosage: "Tempelkan pada luka yang sudah dibersihkan. Ganti setiap hari.",
    manufacturer: "Beiersdorf",
    stock: 250,
  },
  {
    id: 22,
    name: "Chloramphenicol Eye Drop",
    category: "Obat Mata & THT",
    categorySlug: "obat-mata-tht",
    price: 25000,
    image: "/products/chloramphenicol.jpg",
    description: "Chloramphenicol 0.5% tetes mata untuk mengobati infeksi mata bakterial seperti konjungtivitis (mata merah infeksi). Bekerja dengan menghambat pertumbuhan bakteri penyebab infeksi.",
    dosage: "1-2 tetes, 3-4x sehari selama 5-7 hari atau sesuai petunjuk dokter.",
    manufacturer: "Sancopharm",
    stock: 70,
  },
  {
    id: 23,
    name: "Zinc Tablet 20mg",
    category: "Vitamin & Suplemen",
    categorySlug: "vitamin-suplemen",
    price: 32000,
    image: "/products/zinc.jpg",
    description: "Zinc 20mg untuk mendukung pertumbuhan dan perkembangan normal, menjaga fungsi imunitas tubuh, membantu sintesis protein, dan mempercepat penyembuhan luka. Sangat dibutuhkan oleh tubuh setiap hari.",
    dosage: "1 tablet per hari bersama makan.",
    manufacturer: "Generik",
    stock: 140,
  },
  {
    id: 24,
    name: "Oximeter Pulse Digital",
    category: "Alat Kesehatan",
    categorySlug: "alat-kesehatan",
    price: 185000,
    image: "/products/oximeter.jpg",
    description: "Pulse Oximeter digital untuk mengukur kadar oksigen dalam darah (SpO2) dan detak janus dengan cepat dan akurat. Layar OLED besar, baterai tahan lama, dan sangat mudah digunakan.",
    dosage: "Gunakan sesuai panduan penggunaan dalam kemasan.",
    manufacturer: "Contec",
    stock: 40,
    badge: "Unggulan",
  },
];

export const featuredProducts = products.filter(p => p.badge === "Terlaris" || p.badge === "Unggulan" || p.badge === "Promo");

export const formatPrice = (price: number): string => {
  return new Intl.NumberFormat("id-ID", {
    style: "currency",
    currency: "IDR",
    minimumFractionDigits: 0,
  }).format(price);
};
